### ISSUE TITLE
[2.0] Command "/he s" returns incomplete error message when given an invalid gender

### ISSUE THREAD

**Issue by Nevakanezah** [Nevakanezah/HorseEnhancer#57] opened 2023-01-07 01:21 UTC
The he summon command requires that a valid gender is provided, in order to distinguish which type of entity to spawn.
When providing invalid/inaccurate genders to this command, the error message should provide a list of valid selections; currently this is not the case.
![](https://cdn.discordapp.com/attachments/435861888429981717/1061035361595314187/image.png)

**Comment by A-Flying-Poro** [comment] 2023-01-08 21:32
Duplicate of #51, fixed by #52

**Closed by A-Flying-Poro** 2023-01-08 21:32 UTC
Labels: bug, duplicate

**Comment by Nevakanezah** [comment] 2023-01-14 19:33
Confirmed fix
![image](https://user-images.githubusercontent.com/770499/212492897-f537be69-f631-48af-9f01-ac10a1be455b.png)
